server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: userClientService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stocktrade?allowMultiQueries=true
    username: root
    password: yh
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1000MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


