server:
  port: 80 # ?????80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true
      routes:
        -   id: login-service-route
            uri: http://localhost:8088
            predicates:
              - Path=/trade/showTable,/trade/showGraph,/trade/addTrade
              - Method=GET,POST
        -   id: login-service-route2
            uri: http://localhost:8083
            predicates:
              - Path=/tar
              - Method=GET,POST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 3 # ?????????????
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}